---
title: "Exploratory Data Analysis"
subtitle: "STATS 531 Final Project (W21)"
author: "Yanyu Long"
date: "Apr 13, 2021"
output: 
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, #! TODO: switch to FALSE later
  warning = FALSE,
	message = FALSE,
	include = TRUE,
  comment = '',
  fig.align = "center"
)
# rm(list = ls()); rmarkdown::render("main.Rmd")
```

```{css, include = TRUE, echo = FALSE}
pre { /* Scrollable code block */
  max-height: 230px;
  overflow-y: auto;
}
span.math{ /* Formulas */
  font-size: 14px;
}
.comment { /* Comments, to be deleted later */
  margin: 30px;
  padding-left: 10px;
  color: Darkred;
  border-left-style: solid;
  /*border-color: #f2f2f2;*/
  font-weight: 600;
}
table{
  margin-left: auto; /* center the tables */
  margin-right: auto; /* center the tables */
  margin-bottom: 10px; /* add vertical space after table */
}
tr td {
  min-width: 70px;
  height: 35px;
}
tr:nth-child(odd) td {
  background-color: #f9f9f9; /* create the striped effect */
}
```

---

```{r child = 'eda_benchmark.Rmd'}
```

---

```{r child = 'pomp_seir.Rmd'}
```

---

## References

[1] [Michigan Disease Surveillance System (MDSS)](https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html), "Cases and Deaths by County by Date of Onset of Symptoms and Date of Death". Accessed April 7, 2021.
